CREATE TABLE ALUNO (
    CPF CHAR(11) PRIMARY KEY,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(100),
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(15)
);

CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(15),
    FORMACAO VARCHAR(100)
);

CREATE TABLE MODALIDADE (
    ID_MODALIDADE INT PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    TIPO VARCHAR(50)
);

CREATE TABLE TURMA (
    ID_TURMA INT PRIMARY KEY,
    ID_MODALIDADE INT,
    ID_PROFESSOR INT,
    VAGAS INT,
    FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADE(ID_MODALIDADE),
    FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(ID_PROFESSOR)
);

CREATE TABLE MATRICULA (
    ID_MATRICULA INT PRIMARY KEY,
    CPF_ALUNO CHAR(11),
    ID_TURMA INT,
    FOREIGN KEY (CPF_ALUNO) REFERENCES ALUNO(CPF),
    FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
);

CREATE TABLE CARNE (
    ID_CARNE INT PRIMARY KEY,
    DATA_PAGAMENTO DATE,
    VALOR FLOAT,
    CPF_ALUNO CHAR(11),
    FOREIGN KEY (CPF_ALUNO) REFERENCES ALUNO(CPF)
);

CREATE TABLE HORARIO (
    ID_HORARIO INT PRIMARY KEY,
    DIA_SEMANA VARCHAR(20),
    HORA_INICIO TIME,
    HORA_FIM TIME
);

CREATE TABLE TURMA_HORARIO (
    ID_TURMA INT,
    ID_HORARIO INT,
    PRIMARY KEY (ID_TURMA, ID_HORARIO),
    FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA),
    FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

CREATE TABLE PACIENTE (
    CPF_PACIENTE CHAR(11) PRIMARY KEY,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(100),
    TELEFONE VARCHAR(15),
    DATA_NASCIMENTO DATE
);

CREATE TABLE PEDIDO_FISIOTERAPIA (
    ID_PEDIDO INT PRIMARY KEY,
    PLANO VARCHAR(50),
    TIPO_LESAO VARCHAR(100),
    NOME_MEDICO VARCHAR(100),
    CPF_PACIENTE CHAR(11),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF_PACIENTE)
);

CREATE TABLE FISIOTERAPEUTA (
    ID_FISIOTERAPEUTA INT PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(15),
    REGISTRO VARCHAR(50)
);

CREATE TABLE HORARIO_FISIOTERAPIA (
    ID_HORARIO INT,
    ID_PACIENTE CHAR(11),
    ID_FISIOTERAPEUTA INT,
    PRIMARY KEY (ID_HORARIO, ID_PACIENTE, ID_FISIOTERAPEUTA),
    FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(CPF_PACIENTE),
    FOREIGN KEY (ID_FISIOTERAPEUTA) REFERENCES FISIOTERAPEUTA(ID_FISIOTERAPEUTA)
);
